SERIES

In [5]:
import pandas as pd
s = pd.Series([1,2,3,5,np.nan,6,8])
print(s)

0    1.0
1    2.0
2    3.0
3    5.0
4    NaN
5    6.0
6    8.0
dtype: float64


Dataframe con lista nombres, edad y ciudad.

In [4]:
import pandas as pd
data = {'Nombre': ['Fabian', 'Ana', 'Patricia', 'Linda'],
        'Edad': [28, 24, 35, 32],
        'Ciudad': ['Bogota', 'Pereira', 'Bucaramanga', 'Cali']}
df = pd.DataFrame(data)
print(df)

     Nombre  Edad       Ciudad
0    Fabian    28       Bogota
1       Ana    24      Pereira
2  Patricia    35  Bucaramanga
3     Linda    32         Cali


rango de fechas

In [6]:
import pandas as pd
fechas = pd.date_range("2024-01-01", periods=6, freq="M")
print(fechas)

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30'],
              dtype='datetime64[ns]', freq='ME')


<ipython-input-6-34bfac39eadd>:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  fechas = pd.date_range("2024-01-01", periods=6, freq="M")


Metodo to_string

In [10]:
import pandas as pd

df = pd.read_csv('/content/data.csv')
print(df.to_string())

     Duracion  Pulso  Maxpulso  Calorias
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

Crear el DataFrame

In [11]:
import pandas as pd
df = pd.DataFrame(np.random.rand(6,5),index=fechas, columns=list("ABCDE"))
df

A         B         C         D         E
2024-01-31  0.274275  0.428955  0.268959  0.035351  0.251106
2024-02-29  0.198036  0.532787  0.214358  0.386424  0.447613
2024-03-31  0.562346  0.866161  0.079901  0.412199  0.452649
2024-04-30  0.967869  0.090913  0.301380  0.851598  0.985643
2024-05-31  0.397695  0.676716  0.648108  0.122264  0.605785
2024-06-30  0.253097  0.383002  0.463070  0.097680  0.791829

DataFrame con 100 filas y 8 columnas

In [12]:
df1= pd.DataFrame(np.random.rand(100,8))
df1

0         1         2         3         4         5         6  \
0   0.637026  0.635988  0.304382  0.728068  0.294575  0.756136  0.760555   
1   0.154542  0.131196  0.334132  0.948565  0.252032  0.913782  0.631228   
2   0.382922  0.892243  0.651001  0.092171  0.849527  0.230940  0.653383   
3   0.972688  0.066209  0.768160  0.958186  0.796547  0.080509  0.096065   
4   0.026073  0.576117  0.799820  0.957777  0.188962  0.331504  0.088397   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.410089  0.174292  0.503540  0.207296  0.683340  0.577987  0.796660   
96  0.643154  0.670407  0.997603  0.151907  0.912223  0.363434  0.620263   
97  0.071793  0.006203  0.283221  0.544377  0.380901  0.051221  0.174454   
98  0.026641  0.604570  0.336487  0.500263  0.060231  0.435208  0.979301   
99  0.597789  0.554861  0.309882  0.973777  0.544078  0.406863  0.931341   

           7  
0   0.253273  
1   0.616425  
2   0.229167  
3   0.754273  
4   0.325908  
..       ...  
95  0.911393  
96  0.338353  
97  0.956477  
98  0.941958  
99  0.254426  

[100 rows x 8 columns]

Mostrar las primeras filas del DataFrame

In [13]:
import pandas as pd
df1= pd.DataFrame(np.random.rand(100,8))
df1.head(10)

0         1         2         3         4         5         6  \
0  0.460262  0.308163  0.163783  0.517480  0.347007  0.063160  0.449650   
1  0.698411  0.442922  0.072357  0.986520  0.898516  0.211880  0.670347   
2  0.422619  0.993399  0.484408  0.177582  0.788103  0.897290  0.853958   
3  0.110979  0.541908  0.346135  0.514596  0.975012  0.346802  0.838654   
4  0.873748  0.655614  0.723284  0.851742  0.334051  0.447345  0.224147   
5  0.627346  0.509336  0.928617  0.534750  0.709948  0.383670  0.514308   
6  0.004078  0.776036  0.139394  0.328811  0.692610  0.047772  0.864790   
7  0.734713  0.366110  0.502291  0.510365  0.319921  0.287131  0.224459   
8  0.145236  0.834493  0.677998  0.184585  0.649169  0.351414  0.311152   
9  0.233590  0.689381  0.118175  0.089821  0.422125  0.075564  0.015796   

          7  
0  0.528754  
1  0.977520  
2  0.480792  
3  0.976371  
4  0.591960  
5  0.920602  
6  0.566092  
7  0.402375  
8  0.100599  
9  0.768354

 3 filas

In [14]:
df1.tail(3)

0         1         2         3         4         5         6  \
97  0.183369  0.475546  0.114774  0.283183  0.736910  0.521781  0.889748   
98  0.088391  0.113683  0.473501  0.012885  0.046239  0.767837  0.004645   
99  0.117701  0.968862  0.054464  0.542188  0.944875  0.215504  0.558289   

           7  
97  0.190836  
98  0.868569  
99  0.431786

Describir el DataFrame

In [15]:
import pandas as pd
df1= pd.DataFrame(np.random.rand(100,8))
df1.describe()

0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.480192    0.504887    0.469560    0.475266    0.473473    0.441308   
std      0.309386    0.290120    0.289305    0.282205    0.290015    0.308183   
min      0.008928    0.002884    0.003759    0.013673    0.003304    0.008767   
25%      0.225283    0.229445    0.251218    0.230714    0.249973    0.148891   
50%      0.454212    0.523843    0.491227    0.451504    0.426321    0.483405   
75%      0.753046    0.732074    0.728690    0.706219    0.725982    0.693416   
max      0.998310    0.998089    0.992658    0.978120    0.997758    0.973926   

                6           7  
count  100.000000  100.000000  
mean     0.472237    0.470128  
std      0.269907    0.282212  
min      0.006693    0.002557  
25%      0.255259    0.202259  
50%      0.471437    0.482797  
75%      0.680782    0.683604  
max      0.979907    0.991786

Filas máximas

In [16]:
import pandas as pd
print(pd.options.display.max_rows)

60


Aumente el número máximo

In [17]:
import pandas as pd
pd.options.display.max_rows = 9999
df = pd.read_csv('data.csv')
print(df)

     Duracion  Pulso  Maxpulso  Calorias
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

Leer archivos CSV

In [18]:
import pandas as pd
df = pd.read_csv('data.csv')
print(df)

     Duracion  Pulso  Maxpulso  Calorias
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

leen JSON

In [19]:
import pandas as pd
df = pd.read_json('data.json')
print(df.to_string())

     Duracion  Pulso  Maxpulso  Calorias
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

Diccionario en formato JSON

In [20]:
import pandas as pd
data = {
  "Duracion":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulso":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulso":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calorias":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)
print(df)


   Duracion  Pulso  Maxpulso  Calorias
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


Visualización de los datos

In [21]:
import pandas as pd
df= pd.read_csv('data.csv')
print(df.head(10))

   Duracion  Pulso  Maxpulso  Calorias
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0


Creación de Arrays

In [22]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


Crear un array con ceros:  

In [23]:
import numpy as np
arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Crear un array con unos:  

import numpy as np
arr = np.ones((2, 3))  
print(arr)


Crear un array con un rango de valores


In [24]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Crear un array con valores espaciados uniformemente

In [25]:
import numpy as np
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


Operaciones básicas con Arrays

In [26]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Operaciones con escalares:

In [27]:
import numpy as np
print(a * 2)
print(b + 3)

[2 4 6]
[7 8 9]


Operaciones de agregación

In [28]:
import numpy as np
print(a.sum())
print(b.mean())
print(a.max())
print(a.min())


6
5.0
3
1


Manipulación de Arrays

In [30]:
import numpy as np
arr = np.arange(6)
arr = arr.reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


Concatenación de arrays

In [31]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr = np.concatenate((a, b))
print(arr)

[1 2 3 4 5 6]


In [34]:
import numpy as np
a = np.arange(15).reshape(3,5).dtype.name
print(a)

int64


In [33]:
import numpy as np
a = np.arange(15).reshape(3,5).ndim
print(a)

2


In [35]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(type(a))

<class 'numpy.ndarray'>
